### ISSUE TITLE
[BUG] - Error: Failed to initialize build "vultr"

### ISSUE THREAD

**Issue by bbros-dev** [vultr/packer-builder-vultr#114]
**Describe the bug**
`packer build....` produces this error after updating Packer to `1.6.5`

**To Reproduce**
1. Our Chef recipes update Packer to 1.6.5 and Vultr to 2.2.0. These same recipes have installed Packer and Vultr previously.
2. Run `packer build....`
3. See error:

```bash
Error: Failed to initialize build "vultr"

error initializing builder 'vultr': fork/exec
/usr/local/bin/packer-1.6.5/packer-builder-vultr: no such file or directory
```

**Expected behavior**
Packer build proceeds.

**Screenshots**
Not applicable.

**Desktop (please complete the following information where applicable:**
 - OS: Ubuntu 18.04
 - Language Version: 

**Additional context**

```bash
$ ls -la /usr/local/bin/packer
lrwxrwxrwx 1 root root 34 Feb 19 19:39 /usr/local/bin/packer -> /usr/local/bin/packer-1.6.5/packer
```

```bash
$ ls -la ~/.packer.d/plugins/packer-builder-vultr
lrwxrwxrwx 1 root root 62 Feb 19 18:30 /home/<>/.packer.d/plugins/packer-builder-vultr -> /home/<>/.packer.d/plugins/vultr-2.2.0/packer-builder-vultr
```

**Comment by ddymko** [comment]
@bbros-dev 

In the last few days Packer release v1.7.0 which introduced a new design and changes to how plugins interact with Packer. This release was a breaking change as plugins built without the required v1.7.0 changes will not work and plugins built with the required v1.7.0 changes won't work on v1.6.x.

see:
https://github.com/vultr/packer-builder-vultr/releases/tag/v2.2.0
https://github.com/vultr/packer-builder-vultr/pull/110
https://github.com/hashicorp/packer/blob/master/website/content/guides/1.7-plugin-upgrade.mdx

Since you are running on Packer v1.6.5 you have to use the Vultr builder v2.1.0 because v2.2.0 is build for v1.7.0+.
